#!/bin/bash
echo "Starting openfire..."
exec /opt/jdk/bin/java \
      -server \
      -DopenfireHome=/openfire/ \
      -Dopenfire.lib.dir=/openfire/lib \
      -classpath /openfire/.install4j/i4jruntime.jar:/openfire/lib/bcpg-jdk15on.jar:/openfire/lib/bcpkix-jdk15on.jar:/openfire/lib/bcprov-jdk15on.jar:/openfire/lib/hsqldb.jar:/openfire/lib/javax.websocket-api.jar:/openfire/lib/jtds.jar:/openfire/lib/mail.jar:/openfire/lib/mysql.jar:/openfire/lib/npn-boot.jar:/openfire/lib/openfire.jar:/openfire/lib/postgres.jar:/openfire/lib/slf4j-log4j12.jar:/openfire/lib/startup.jar \
      -jar /openfire/lib/startup.jar
